#! /bin/sh

# Jazzio Labs Autotools support
# @(#) $Id$

# Copyright (c) 2003, 2004, 2005, 2006, 2007, 2008, 2009 Mo McRoberts.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The names of the author(s) of this software may not be used to endorse
#    or promote products derived from this software without specific prior
#    written permission.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, 
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
# AUTHORS OF THIS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

AUTOHEADER26=${AUTOHEADER26-autoheader26}
LIBTOOLIZE15=${LIBTOOLIZE15-libtoolize15}
ACLOCAL110=${ACLOCAL110-aclocal110}
AUTOMAKE110=${AUTOMAKE110-automake110}
AUTOCONF26=${AUTOCONF26-autoconf26}
AUTORECONF=${AUTORECONF-autoreconf}

appname="$0"
srcdir="`pwd`"
toolsdir="`dirname \"$appname\"`"
toolsdir="`(cd \"$toolsdir\" && pwd)`"

fail() {
	echo "$appname: $*" >&2
	exit 1
}

oprogress() {
	echo ">>> $*"
}
progress() {
	echo " +> $*"
}

if test -r "$srcdir/autogen.rc" ; then
	. "$srcdir/autogen.rc"
fi

if test x"${SUBDIRS}" = x"" ; then
	true
else
	for i in ${SUBDIRS} ; do
		if test -d "$i" ; then
			( cd "$srcdir/$i" && "$toolsdir/autogen" ) || exit $?
		else
			echo "autogen: $srcdir/$i does not exist" >&2
		fi
	done
fi

if test x"${DECL_H_PATH}" = x"" || test x"${DECL_H_PREFIX}" = x"" ; then
	true
else
	sed -e "s!%PREFIX%!${DECL_H_PREFIX}!g" < "$toolsdir/decl.h.in" > "${DECL_H_PATH}.in"
	if test -r "${DECL_H_PATH}" && diff "${DECL_H_PATH}" "${DECL_H_PATH}.in" >/dev/null ; then
		progress "${DECL_H_PATH} is unchanged"
		rm -f "${DECL_H_PATH}.in"
	else
		progress "Installing ${DECL_H_PATH}"
		mv "${DECL_H_PATH}.in" "${DECL_H_PATH}"
	fi
fi

test -r "$srcdir/configure.ac" || fail "Cannot find configure.ac in $srcdir"

if test -f autogen.sh ; then
	oprogress "Running autoreconf to generate files"
	${AUTORECONF} -f -i
	exit
fi
oprogress "Generating files in $srcdir"
progress "Generating aclocal.m4"
aclocalopts="-I$toolsdir"
if test -d "$srcdir/m4" ; then
	aclocalopts="$aclocalopts -I$srcdir/m4"
fi
${ACLOCAL110} $aclocalopts || exit

if egrep '^AC_CONFIG_HEADER' "$srcdir/configure.ac" >/dev/null ; then
	progress "Generating config.h.in"
	${AUTOHEADER26} || exit
fi
if egrep '^AC_PROG_LIBTOOL' "$srcdir/configure.ac" >/dev/null ; then
	progress "Generating ltmain.sh"
	${LIBTOOLIZE15} --force --copy --automake || exit
fi

if egrep "^AM_INIT_AUTOMAKE" "$srcdir/configure.ac" >/dev/null ; then
	progress "Generating Makefile.in from Makefile.am"
	${AUTOMAKE110} --add-missing --copy || exit
fi

progress "Generating configure script"
${AUTOCONF26} || exit
